---
kind: Namespace
apiVersion: v1
metadata:
  name: egress-demo
  labels:
    app: frr-router
---
kind: NodeNetworkConfigurationPolicy
apiVersion: nmstate.io/v1
metadata:
  name: bond0.1410
  labels:
    app: frr-router
spec:
  desiredState:
    interfaces:
      - name: bond0.1410
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 1410
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: bridge-1410
        type: linux-bridge
        state: up
        bridge:
          port:
          - name: bond0.1410
---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  annotations:
    description: Machine Network Attachment
  labels:
    app: frr-router
  name: virtualmachine-net
  namespace: egress-demo
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "virtualmachine-net",
      "type": "bridge",
      "bridge": "bridge-1410",
      "promiscMode": true
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frr-router-cloud-init
  namespace: egress-demo
  labels:
    app: frr-router
data:
  frr.sh: |-
    nmcli con mod "System eth0" \
      ipv4.addresses "10.14.10.98/24" \
      ipv4.gateway "10.14.10.1" \
      ipv4.dns "10.14.1.8 8.8.8.8" \
      ipv4.ignore-auto-dns yes \
      ipv4.method manual
    nmcli con up "System eth0"
    subscription-manager register --org=13225056 --activationkey=homelab

    dnf install -y frr
    systemctl enable frr
    systemctl stop frr
    sed -i 's/^bgpd=no/bgpd=yes/' /etc/frr/daemons
    sed -i 's/^bfdd=no/bfdd=yes/' /etc/frr/daemons
    sed -i 's/^zebra=no/zebra=yes/' /etc/frr/daemons
    echo "
    frr version 8.5.3
    frr defaults traditional
    hostname frr-bgp-router
    log file /var/log/frr/frr.log
    no ip forwarding
    no ipv6 forwarding
    !
    ! BFD Global Configuration
    !
    bfd
     peer-detect-multiplier 5
     min-rx-interval 100
     min-tx-interval 100
    !
    ! BGP Configuration
    !
    router bgp 65001
     bgp router-id 10.14.10.98
     no bgp ebgp-requires-policy
     neighbor 10.14.10.13 remote-as 64511
     neighbor 10.14.10.14 remote-as 64511
     neighbor 10.14.10.15 remote-as 64511
     neighbor 10.14.10.23 remote-as 64512
     neighbor 10.14.10.24 remote-as 64512
     neighbor 10.14.10.25 remote-as 64512
     neighbor 10.14.10.33 remote-as 64513
     neighbor 10.14.10.34 remote-as 64513
     neighbor 10.14.10.35 remote-as 64513
     neighbor 10.14.10.13 bfd
     neighbor 10.14.10.14 bfd
     neighbor 10.14.10.15 bfd
     neighbor 10.14.10.23 bfd
     neighbor 10.14.10.24 bfd
     neighbor 10.14.10.25 bfd
     neighbor 10.14.10.33 bfd
     neighbor 10.14.10.34 bfd
     neighbor 10.14.10.35 bfd
     !
     address-family ipv4 unicast
      neighbor 10.14.10.13 soft-reconfiguration inbound
      neighbor 10.14.10.14 soft-reconfiguration inbound
      neighbor 10.14.10.15 soft-reconfiguration inbound
      neighbor 10.14.10.23 soft-reconfiguration inbound
      neighbor 10.14.10.24 soft-reconfiguration inbound
      neighbor 10.14.10.25 soft-reconfiguration inbound
      neighbor 10.14.10.33 soft-reconfiguration inbound
      neighbor 10.14.10.34 soft-reconfiguration inbound
      neighbor 10.14.10.35 soft-reconfiguration inbound
     exit-address-family
    exit
    !
    " > /etc/frr/frr.conf
    chown frr:frr /etc/frr/frr.conf
    systemctl start frr
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: frr-bgp-router
  namespace: egress-demo
  labels:
    app: frr-router
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: frr-bgp-router-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    kind: virtualmachineclusterinstancetype
    name: u1.2xmedium
  preference:
    kind: virtualmachineclusterpreference
    name: rhel.9
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        network.kubevirt.io/headlessService: headless
        app: frr-router
    spec:
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: frr-script
              serial: frr
          interfaces:
            - bridge: {}
              macAddress: '02:9e:d1:00:00:01'
              model: virtio
              name: machine-net
              state: up
        machine:
          type: pc-q35-rhel9.6.0
        resources: {}
      networks:
        - multus:
            networkName: virtualmachine-net
          name: machine-net
      subdomain: headless
      volumes:
        - name: rootdisk
          dataVolume:
            name: frr-bgp-router-volume
        - name: frr-script
          configMap:
            name: frr-router-cloud-init
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              ethernets:
                eth0:
                  addresses:
                    - 10.14.10.98/24
                  gateway: 10.14.1.1
                  nameservers:
                    addresses:
                      - 10.14.1.8
                      - 8.8.8.8
                      - 8.8.4.4
              version: 2
            userData: |
              #cloud-config
              hostname: frr-external-router
              users:
                - name: rhel
                  password: redhat
                  chpasswd:
                    expire: false
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmgS4N8a5rkWDs5YD0XxFEbJwdllmfBC6k4j694UsAbUlTDLnfCTPlZkYYg7ME7F8ipZWVjZn6p1H6Esn+CvNYxQGQjgh8zBk+87jITMGYWSzfKQVSYE4J1hqhWHnqQeWwXAm30lcdK0IyTHUQMnF4HosIdNB6n2F2+KRUINP8fx0x6lRVZsOvhYdbSMF4Q6hZMOrN5CRvZjcYOu+WVaNPtaWfuzNhoxKzN7boe6On9+oaOiMV17DQ5bHdLIHY+aiMP3WKZOF37LzHIMGB9TxcfwodgFI8EmHXZM3wQlPDic2oR65WazhmaeZ5RvXkjBKe3mkAwTRWMKpwcVHdvnhGAKDUphmTOOZi978eKtXYODRnduA0FH2TVgCS8bBk6OSJP/fZCH3NGf9DnvT83myi8CPfV31U7RIffPX+E3wLFyab+gDSRwQ1lX1oQf/822CKdDD9lHYp+MrYeANCNSxLVmI/XO5V3aOVtvNW29Nq8tAX/BzR62vvWLSw+LattFc=
              runcmd:
                - mount /dev/disk/by-id/virtio-frr /mnt/
                - bash /mnt/frr.sh
                - umount /mnt

