---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
  namespace: metallb-system
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  name: metallb-operator
  channel: "stable"
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec: {}
---
apiVersion: metallb.io/v1beta1
kind: BFDProfile
metadata:
  name: bfd-tuning
  namespace: metallb-system
spec:
  detectMultiplier: 37
  echoMode: true
  minimumTtl: 10
  passiveMode: true
  receiveInterval: 35
  transmitInterval: 35
---
# 1. BGPPeer: Defines the connection to your external router
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: external-router
  namespace: metallb-system
spec:
  peerAddress: 10.14.10.98
  peerASN: 65001
  myASN: 64512 
  nodeSelectors:
  - matchLabels:
      k8s.ovn.org/egress-assignable: ""
---
# 2. IPAddressPool: Defines the network range that Egress IPs will be sourced from/advertised in.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: egress-ip-pool
  namespace: metallb-system
spec:
  protocol: bgp
  autoAssign: yes
  addresses:
  - 10.14.10.100/32
  - 10.14.10.101/32
  - 10.14.10.102/32
  - 10.14.10.103/32
---
# 3. BGPAdvertisement: Instructs MetalLB to advertise the routes in the defined pool.
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: egress-ip-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - egress-ip-pool
  peers:
  - external-router
